inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

LineLength:
  Enabled: false

SignalException:
  Enabled: false

# Don't care enough about this one
SpaceInsideHashLiteralBraces:
  Enabled: false

# Using $CHILD_STATUS instead of $?, etc
SpecialGlobalVars:
  Enabled: false

StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: false
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

# disabling a bunch of style linters
Lint/BlockAlignment:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/Void:
  Exclude:
    - dashboard/spec/**/*

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MethodCallParentheses:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAfterNot:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

# As of rubocop 0.21, it thinks kwargs are useless assignments
UselessAssignment:
  Enabled: false

WordArray:
  Enabled: false
